apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-simple
  name: nginx-simple
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-simple
  template:
    metadata:
      labels:
        app: nginx-simple
    spec:
      containers:
      - image: nginx
        name: nginx